name: greys_corp
description: Grey's Corp's Official Aplication

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images

  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700

   #- family: Schyler
   #  fonts:
   #    - asset: fonts/Schyler-Regular.ttf
   #    - asset: fonts/Schyler-Italic.ttf
   #      style: italic
   #- family: Trajan Pro
   #  fonts:
   #    - asset: fonts/TrajanPro.ttf
   #    - asset: fonts/TrajanPro_Bold.ttf
   #      weight: 700

